# -*- coding: utf-8 -*-
"""Final --  Hackhaton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6rKwzuJT-b3ZviMYEvcxK1HJKzrHwUO
"""

import os
from groq import Groq

# --- 1. MOCK IMPORTS FOR COLAB TESTING ---
def run_water_calculations(farm_inputs):
    return f"Engine Tool Triggered: Calculating water needs for '{farm_inputs}'"

def answer_question_with_rag(question):
    return f"RAG Tool Triggered: Searching documents for '{question}'"


# --- 2. SCENARIO INTELLIGENCE TOOL ---
def compare_scenarios(baseline_volume, alternative_volume):
    """Calculates the potential scenario difference in groundwater volume."""
    saved_water = baseline_volume - alternative_volume

    if saved_water > 0:
        return f"Scenario Tool Triggered: By switching to the alternative scenario, you save {saved_water} cubic meters of groundwater."
    else:
        return "Scenario Tool Triggered: The alternative scenario does not save groundwater compared to the baseline."


# --- 3. REPORT GENERATOR & GUARDRAIL ---
def require_human_confirmation():
    """Guardrail: Prevents the agent from finalizing without user permission."""
    return "System Guardrail: I have drafted a water account report based on your inputs. Do you want to finalize and view the export? (Type 'Yes' to confirm)."

def generate_final_report(calculation_results, scenario_results, rag_evidence):
    """Compiles the structured results and cited evidence into a final summary."""
    report = f"""
    *** AQUAGUARD AI: FINAL WATER ACCOUNT REPORT ***

    1. Water Calculations:
    {calculation_results}

    2. Scenario Comparison (Intelligence):
    {scenario_results}

    3. Document Evidence (RAG):
    {rag_evidence}

    Disclaimer: These outputs are modelled estimates, not direct measurements of actual pumping.
    """
    return report


# --- 4. THE AI AGENT ROUTER ---
def route_user_request(user_message, api_key):
    """Uses Groq to decide which tool to use based on the user's message."""

    client = Groq(api_key=api_key)

    system_prompt = """
    You are an AI router for the AquaGuard agriculture app.
    Read the user's message and reply with ONLY ONE exact word from this list:
    - CALCULATE (if the user wants to calculate water needs, crop demand, or irrigation volume)
    - COMPARE (if the user wants to compare two irrigation scenarios)
    - SEARCH (if the user is asking a general knowledge question about farming, crops, or groundwater)

    Do not add any other words, greetings, or punctuation.
    """

    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message}
        ],
        model="openai/gpt-oss-20b",
        temperature=0.0
    )

    decision = response.choices[0].message.content.strip().upper()
    print(f"Agent Routing Decision: {decision}")

    # --- EXECUTION GATEWAY ---
    if "CALCULATE" in decision:
        return run_water_calculations(user_message)
    elif "COMPARE" in decision:
        return compare_scenarios(5000, 3500)
    elif "SEARCH" in decision:
        return answer_question_with_rag(user_message)
    else:
        return "System Guardrail: Request not recognized."